import pizza_beef from "../../images/pizza-beef.jpeg";
import pizza_beef_1 from "../../images/pizza-beef-1.jpeg";
import pizza_beef_2 from "../../images/pizza-beef-2.jpeg";
import pizza_beef_3 from "../../images/pizza-beef-3.jpeg";
import pizza_beef_onion from "../../images/pizza-oninion.jpeg";
export const PizzaList = [
  {
    id: 1,
    category: "beef",
    name: "Delux Feast",
    price: 20,
    url: pizza_beef,
    quantity: 1,
    rating: 4,
    size: "small",
  },
  {
    id: 2,
    category: "beef",
    name: "Phily Cheese Steak",
    price: 15,
    url: pizza_beef_1,
    quantity: 1,
    rating: 3,
    size: "small",
  },
  {
    id: 3,
    category: "beef",
    name: "Meatzza Feast",
    price: 18,
    url: pizza_beef_2,
    quantity: 1,
    rating: 5,
    size: "medium",
  },
  {
    id: 4,
    category: "beef",
    name: "Hot & Spicy Feast",
    price: 23,
    url: pizza_beef_3,
    quantity: 1,
    rating: 4,
    size: "small",
  },
  {
    id: 5,
    category: "chicken",
    name: "BBQ Feast",
    price: 23,
    url: pizza_beef_onion,
    quantity: 1,
    rating: 4,
    size: "large",
  },
  {
    id: 6,
    category: "chicken",
    name: "Tex-Mex Feast",
    price: 23,
    url: pizza_beef,
    quantity: 1,
    rating: 5,
    size: "large",
  },
  {
    id: 7,
    category: "chicken",
    name: "Chicken Legend Ranch",
    price: 23,
    url: pizza_beef_3,
    quantity: 1,
    rating: 5,
    size: "large",
  },
  {
    id: 8,
    category: "chicken",
    name: "Chicken Legend BBQ",
    price: 23,
    url: pizza_beef_2,
    quantity: 1,
    rating: 5,
    size: "medium",
  },
  {
    id: 9,
    category: "chicken",
    name: "Chicken Legend Hot",
    price: 23,
    url: pizza_beef_2,
    quantity: 1,
    rating: 5,
    size: "medium",
  },
  {
    id: 10,
    category: "chicken",
    name: "Kickers Pizza BBQ Sauce",
    price: 23,
    url: pizza_beef_1,
    quantity: 1,
    rating: 3,
    size: "medium",
  },
  {
    id: 11,
    category: "pepperoni",
    name: "Extravaganzza Feast",
    price: 25,
    url: pizza_beef_2,
    quantity: 1,
    rating: 3,
    size: "medium",
  },
  {
    id: 12,
    category: "pepperoni",
    name: "Hawaiian Feast",
    price: 40,
    url: pizza_beef_3,
    quantity: 1,
    rating: 4,
    size: "medium",
  },
  {
    id: 13,
    category: "pepperoni",
    name: "Italiano Feast",
    price: 12,
    url: pizza_beef_1,
    quantity: 1,
    rating: 4,
    size: "small",
  },
  {
    id: 14,
    category: "pepperoni",
    name: "Meatzza Feast",
    price: 24,
    url: pizza_beef,
    quantity: 1,
    rating: 4,
    size: "small",
  },
  {
    id: 15,
    category: "cheese",
    name: "Margherita",
    price: 35,
    url: pizza_beef_onion,
    quantity: 1,
    rating: 4,
    size: "small",
  },
  {
    id: 16,
    category: "cheese",
    name: "Phily Cheese Steak",
    price: 50,
    url: pizza_beef_2,
    quantity: 1,
    rating: 4,
    size: "large",
  },
  {
    id: 17,
    category: "special",
    name: "Pepperoni Feast",
    price: 60,
    url: pizza_beef,
    quantity: 1,
    rating: 5,
    size: "large",
  },
  {
    id: 18,
    category: "special",
    name: "Kickers Pizza BBQ Sauce",
    price: 75,
    url: pizza_beef_onion,
    quantity: 1,
    rating: 5,
    size: "large",
  },
  {
    id: 19,
    category: "special",
    name: "Alfredo Pizza",
    price: 70,
    url: pizza_beef_3,
    quantity: 1,
    rating: 5,
    size: "medium",
  },

  {
    id: 20,
    category: "special",
    name: "Alfredo Pizza",
    price: 70,
    url: pizza_beef_3,
    quantity: 1,
    rating: 5,
    size: "medium",
  },

  {
    id: 21,
    category: "beef",
    name: "Alfredomagnito Pizza",
    price: 70,
    url: pizza_beef_3,
    quantity: 1,
    rating: 4,
    size: "large",
  },
];
